/**
 * Auto-generated by openapi-typescript. Do not edit manually.
 * Run `pnpm openapi:generate` to regenerate.
 */

// Placeholder — replace with generated types once the OpenAPI spec is available
export interface paths {
  [path: string]: {
    [method: string]: unknown
  }
}

// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface components {}
