/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/v1/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a test generation request
         * @description Validates the request, stores it in DynamoDB as "pending", and enqueues it for asynchronous generation. Returns the test ID immediately.
         */
        post: operations["createTest"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a generated test by ID
         * @description Retrieves the test item from DynamoDB. When status is "pending", the test_response field will not be present. When status is "completed", the full generated test is included.
         */
        get: operations["getTest"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/tests": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List tests
         * @description Returns a paginated list of all tests. Use limit and last_key for pagination.
         */
        get: operations["listTestsV2"];
        put?: never;
        /**
         * Create a test generation request
         * @description Validates the request, stores it in DynamoDB as "pending", and enqueues it for asynchronous generation. Returns the test ID immediately.
         */
        post: operations["createTestV2"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/materials/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload a PDF for RAG-powered test generation
         * @description Accepts a PDF file and computes a content hash for deduplication. For new uploads, the PDF is queued for asynchronous ingestion (chunking + embedding) and the endpoint returns **202 Accepted** immediately with `status: "processing"`; poll `GET /v2/materials/{material_id}` until `status` is `"ready"` before referencing the material in test generation. For duplicates (same content hash), the existing material's TTL is refreshed and **200 OK** is returned with the already-known `chunk_count` / `page_count`. Materials expire automatically after 24 hours.
         */
        post: operations["uploadMaterial"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/materials/{material_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get material status and metadata
         * @description Poll this endpoint after `POST /v2/materials/upload` to check ingestion status. While `status='processing'`, chunk_count and page_count are null. Once `status='ready'`, the material can be referenced in test generation.
         */
        get: operations["getMaterial"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v2/tests/{testId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a generated test by ID
         * @description Retrieves the test item from DynamoDB. When status is "pending", the test_response field will not be present. When status is "completed", the full generated test is included.
         */
        get: operations["getTestV2"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        MaterialUploadResponse: {
            /** Format: uuid */
            material_id: string;
            filename: string;
            /** @description True if a previously-uploaded file with identical content was found */
            is_duplicate: boolean;
            /**
             * @description - `processing`: ingestion in progress (only returned for new uploads)
             *     - `ready`: ingestion complete (only returned for duplicates that already finished)
             *     - `failed`: previous ingestion of this content failed (only for duplicates)
             * @enum {string}
             */
            status: "processing" | "ready" | "failed";
            /** @description Number of chunks. Null while status='processing'. */
            chunk_count?: number | null;
            /** @description Number of pages. Null while status='processing'. */
            page_count?: number | null;
            /** Format: date-time */
            expires_at: string;
        };
        MaterialStatus: {
            /** Format: uuid */
            material_id: string;
            filename: string;
            /** @enum {string} */
            status: "processing" | "ready" | "failed";
            chunk_count?: number | null;
            page_count?: number | null;
            /** Format: date-time */
            expires_at: string;
            /** @description Error message if status='failed', otherwise null */
            error?: string | null;
        };
        CreateTestRequest: {
            test_request: components["schemas"]["GenerationRequest"];
        };
        /** @description At least one question type must have amount > 0. Question types not included (or with amount: 0) are skipped. */
        GenerationRequest: {
            /**
             * @description The subject of the test (e.g. "English Grammar", "Mathematics")
             * @example English Grammar
             */
            subject: string;
            /**
             * @description Difficulty level of generated questions
             * @default intermediate
             * @enum {string}
             */
            difficulty_level: "beginner" | "intermediate" | "advanced";
            /**
             * @description Language for the generated test content
             * @default English
             * @example Czech
             */
            language: string;
            mcq_single?: components["schemas"]["QuestionTypeConfig"];
            mcq_multiple?: components["schemas"]["QuestionTypeConfig"];
            open_ended?: components["schemas"]["QuestionTypeConfig"];
            true_false?: components["schemas"]["QuestionTypeConfig"];
            fill_in?: components["schemas"]["QuestionTypeConfig"];
            ordering?: components["schemas"]["QuestionTypeConfig"];
            pairs?: components["schemas"]["QuestionTypeConfig"];
            categorization?: components["schemas"]["QuestionTypeConfig"];
            short_answer?: components["schemas"]["QuestionTypeConfig"];
            numeric?: components["schemas"]["QuestionTypeConfig"];
        };
        QuestionTypeConfig: {
            /**
             * @description Number of questions to generate for this type
             * @default 0
             */
            amount: number;
            /**
             * @description Optional topic override for this question type. Falls back to the main subject if not provided.
             * @example Present tenses
             */
            topic?: string | null;
        };
        CreateTestResponse: {
            /**
             * Format: uuid
             * @description Unique identifier for the created test
             */
            test_id: string;
        };
        ErrorResponse: {
            /** @description Human-readable error message */
            error: string;
        };
        /** @description The test_response field is only present when status is "completed". */
        TestItem: {
            /**
             * Format: uuid
             * @description Unique identifier for the test
             */
            id: string;
            /**
             * @description "pending" while the test is being generated, "completed" once generation has finished, "failed" if the agent encountered an error.
             * @enum {string}
             */
            status: "pending" | "completed" | "failed";
            test_request: components["schemas"]["GenerationRequest"];
            test_response?: components["schemas"]["GenerationResponse"];
        };
        GenerationResponse: {
            metadata: components["schemas"]["ResponseMetadata"];
            questions: components["schemas"]["ResponseQuestion"][];
            /**
             * @description ID of the AI model used for generation
             * @example claude-haiku
             */
            model_id: string;
            /**
             * @description Total generation time in milliseconds
             * @example 4500
             */
            generation_time_ms: number;
            /**
             * @description Number of retries needed during generation
             * @example 0
             */
            retry_count: number;
        };
        ResponseMetadata: {
            /**
             * @description Generated test name
             * @example English Grammar Test
             */
            name: string;
            /**
             * @description Suggested time limit in minutes
             * @example 15
             */
            time_limit_min: number;
            /**
             * @description Main topic of the test
             * @example English Grammar
             */
            topic?: string;
            /**
             * @description Difficulty level label
             * @example intermediate
             */
            level?: string;
            /**
             * @description Language of the test
             * @example Czech
             */
            language?: string;
        };
        ResponseQuestion: components["schemas"]["McqSingleQuestion"] | components["schemas"]["McqMultipleQuestion"] | components["schemas"]["OpenEndedQuestion"] | components["schemas"]["TrueFalseQuestion"] | components["schemas"]["FillInQuestion"] | components["schemas"]["OrderingQuestion"] | components["schemas"]["PairsQuestion"] | components["schemas"]["CategorizationQuestion"] | components["schemas"]["ShortAnswerQuestion"] | components["schemas"]["NumericQuestion"];
        /** @description Multiple choice question with a single correct answer. */
        McqSingleQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MCQ_SINGLE";
            /** @description The question text */
            question: string;
            /** @description Answer options with exactly 1 correct */
            options: components["schemas"]["ResponseOption"][];
        };
        /** @description Multiple choice question with multiple correct answers. */
        McqMultipleQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "MCQ_MULTIPLE";
            /** @description The question text */
            question: string;
            /** @description Answer options with 2 or more correct */
            options: components["schemas"]["ResponseOption"][];
        };
        /** @description Open-ended question evaluated by keyword presence. */
        OpenEndedQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "OPEN_ENDED";
            /** @description The question text */
            question: string;
            /** @description Keywords expected in the answer */
            correct_keywords: string[];
        };
        /** @description True/false question. */
        TrueFalseQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "TRUE_FALSE";
            /** @description The question text */
            question: string;
            /** @description The correct answer (true or false) */
            is_true: boolean;
        };
        /** @description Fill-in-the-blank question with multiple choice options. */
        FillInQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "FILL_IN";
            /** @description The question text. Contains exactly one "___" blank to be filled. */
            question: string;
            /** @description Exactly 4 answer options with exactly 1 correct */
            options: components["schemas"]["ResponseOption"][];
        };
        /** @description Question where items must be placed in the correct order. */
        OrderingQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "ORDERING";
            /** @description The question text */
            question: string;
            /** @description Items with their correct order (correct_index 1..N) */
            ordering_items: components["schemas"]["ResponseOrderingItem"][];
            /** @description Shuffled items displayed to the student */
            display_items: string[];
        };
        /** @description Matching/pairing question. */
        PairsQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "PAIRS";
            /** @description The question text */
            question: string;
            /** @description Correct item pairings */
            pair_items: components["schemas"]["ResponsePairItem"][];
            /** @description Shuffled left-side items */
            item_a_options: string[];
            /** @description Shuffled right-side items */
            item_b_options: string[];
        };
        /** @description Question where items must be sorted into categories. */
        CategorizationQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "CATEGORIZATION";
            /** @description The question text */
            question: string;
            /** @description Items grouped by their correct category */
            category_items: components["schemas"]["ResponseCategoryItems"][];
            /** @description Shuffled category names */
            categories: string[];
            /** @description Shuffled items to be categorized */
            item_options: string[];
        };
        /** @description Short answer question with a list of acceptable answers. */
        ShortAnswerQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "SHORT_ANSWER";
            /** @description The question text */
            question: string;
            /** @description Acceptable answers */
            possible_answers: string[];
        };
        /** @description Question with a numeric answer and optional tolerance. */
        NumericQuestion: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "NUMERIC";
            /** @description The question text */
            question: string;
            /** @description The correct numeric answer */
            answer: number;
            /** @description Acceptable tolerance for the answer (>= 0) */
            tolerance?: number;
        };
        ResponseOption: {
            /**
             * @description Option label (A, B, C, ...)
             * @example A
             */
            label: string;
            /**
             * @description Option text
             * @example She goes to school every day.
             */
            text: string;
            /** @description Whether this option is correct */
            is_correct: boolean;
        };
        ResponseOrderingItem: {
            /** @description The item text */
            text: string;
            /** @description Correct position in the sequence (1-based) */
            correct_index: number;
        };
        ResponsePairItem: {
            /** @description Left-side item */
            item_a: string;
            /** @description Right-side matching item */
            item_b: string;
        };
        ResponseCategoryItems: {
            /** @description Category name */
            category: string;
            /** @description Items belonging to this category */
            items: string[];
        };
        ListTestsResponse: {
            items: components["schemas"]["TestItemV2"][];
            /** @description Total number of tests in the table */
            total: number;
            /** @description Limit used for this request */
            limit: number;
            /** @description Offset used for this request */
            offset: number;
        };
        CreateTestRequestV2: {
            test_request: components["schemas"]["GenerationRequestV2"];
        };
        GenerationRequestV2: {
            /**
             * @description The subject of the test (e.g. "English Grammar", "Mathematics")
             * @example English Grammar
             */
            subject: string;
            /**
             * @description Difficulty level of generated questions
             * @default intermediate
             * @enum {string}
             */
            difficulty_level: "beginner" | "intermediate" | "advanced";
            /**
             * @description Language for the generated test content
             * @default English
             * @example Czech
             */
            language: string;
            /** @description List of question groups to generate */
            groups: components["schemas"]["GroupConfig"][];
        };
        GroupConfig: {
            /**
             * @description Display name for this group
             * @example Present Tenses
             */
            name: string;
            /**
             * @description Question type for all questions in this group
             * @enum {string}
             */
            type: "MCQ_SINGLE" | "MCQ_MULTIPLE" | "OPEN_ENDED" | "TRUE_FALSE" | "FILL_IN" | "ORDERING" | "PAIRS" | "CATEGORIZATION" | "SHORT_ANSWER" | "NUMERIC";
            /**
             * @description Number of questions to generate for this group
             * @example 5
             */
            amount: number;
            /**
             * @description Optional topic override for this group. Falls back to the main subject if not provided.
             * @example Present tenses
             */
            topic?: string | null;
            rag?: components["schemas"]["GroupRAGConfig"];
        };
        /** @description Optional RAG configuration for a group. When present, the group's questions are generated from context retrieved from the uploaded material rather than the LLM's general knowledge. */
        GroupRAGConfig: {
            /**
             * Format: uuid
             * @description UUID returned from POST /v2/materials/upload. Must reference a material that has not expired (24h TTL).
             * @example a1b2c3d4-e5f6-7890-abcd-ef1234567890
             */
            material_id: string;
            /**
             * @description Override the similarity search query. Defaults to the group's topic or the request's subject if not provided.
             * @example Hash table collision resolution
             */
            topic?: string | null;
            /**
             * @description Number of chunks to retrieve from the material. Lower values (2-4) produce focused, passage-specific questions. Higher values (10+) produce broader questions covering more of the document. Each chunk is ~1000 characters.
             * @default 6
             */
            num_chunks: number;
        };
        /** @description The test_response field is only present when status is "completed". */
        TestItemV2: {
            /**
             * Format: uuid
             * @description Unique identifier for the test
             */
            id: string;
            /**
             * @description "pending" while the test is being generated, "completed" once generation has finished, "failed" if the agent encountered an error.
             * @enum {string}
             */
            status: "pending" | "completed" | "failed";
            test_request: components["schemas"]["GenerationRequestV2"];
            test_response?: components["schemas"]["GenerationResponseV2"];
        };
        GenerationResponseV2: {
            metadata: components["schemas"]["ResponseMetadata"];
            /** @description Successfully generated question groups */
            groups: components["schemas"]["ResponseGroup"][];
            /** @description Groups that failed to generate after all retries */
            failed_groups: components["schemas"]["FailedGroup"][];
            /**
             * @description ID of the AI model used for generation
             * @example anthropic.claude-haiku-20240307-v1:0
             */
            model_id: string;
            /**
             * @description Total generation time in milliseconds
             * @example 4500
             */
            generation_time_ms: number;
            /**
             * @description Total number of retries across all groups
             * @example 1
             */
            total_retries: number;
        };
        ResponseGroup: {
            /** @description Group name matching the request */
            name: string;
            /** @enum {string} */
            type: "MCQ_SINGLE" | "MCQ_MULTIPLE" | "OPEN_ENDED" | "TRUE_FALSE" | "FILL_IN" | "ORDERING" | "PAIRS" | "CATEGORIZATION" | "SHORT_ANSWER" | "NUMERIC";
            /** @description Topic used for this group (from request or fallback to subject) */
            topic?: string | null;
            questions: components["schemas"]["ResponseQuestion"][];
        };
        FailedGroup: {
            /** @description Group name matching the request */
            name: string;
            /** @enum {string} */
            type: "MCQ_SINGLE" | "MCQ_MULTIPLE" | "OPEN_ENDED" | "TRUE_FALSE" | "FILL_IN" | "ORDERING" | "PAIRS" | "CATEGORIZATION" | "SHORT_ANSWER" | "NUMERIC";
            /** @description Number of questions that were requested */
            amount: number;
            topic?: string | null;
            /** @description Reason for failure */
            error: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    createTest: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                /**
                 * @example {
                 *       "test_request": {
                 *         "subject": "English Grammar",
                 *         "difficulty_level": "intermediate",
                 *         "language": "Czech",
                 *         "mcq_single": {
                 *           "amount": 5,
                 *           "topic": "Present tenses"
                 *         },
                 *         "mcq_multiple": {
                 *           "amount": 2,
                 *           "topic": "Modal verbs"
                 *         },
                 *         "true_false": {
                 *           "amount": 3,
                 *           "topic": "Subject-verb agreement"
                 *         }
                 *       }
                 *     }
                 */
                "application/json": components["schemas"]["CreateTestRequest"];
            };
        };
        responses: {
            /** @description Test request accepted and enqueued for generation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "test_id": "550e8400-e29b-41d4-a716-446655440000"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateTestResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Missing required field: test_request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTest: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the test */
                testId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestItem"];
                };
            };
            /** @description Test not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Test 550e8400-e29b-41d4-a716-446655440000 not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    listTestsV2: {
        parameters: {
            query?: {
                /** @description Maximum number of items to return (1–100, default 20) */
                limit?: number;
                /** @description Number of items to skip (default 0) */
                offset?: number;
                /** @description Case-insensitive substring search applied across test_request fields: subject, language, and each group's name and topic. */
                search?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated list of tests */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ListTestsResponse"];
                };
            };
            /** @description Invalid query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    createTestV2: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTestRequestV2"];
            };
        };
        responses: {
            /** @description Test request accepted and enqueued for generation */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "test_id": "550e8400-e29b-41d4-a716-446655440000"
                     *     }
                     */
                    "application/json": components["schemas"]["CreateTestResponse"];
                };
            };
            /** @description Validation error */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Missing required field: test_request"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Internal server error */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    uploadMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /**
                     * Format: binary
                     * @description PDF file to upload (max 50 MB)
                     */
                    file: string;
                };
            };
        };
        responses: {
            /** @description PDF was a duplicate of a previous upload — TTL refreshed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadResponse"];
                };
            };
            /** @description PDF accepted for asynchronous ingestion */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialUploadResponse"];
                };
            };
            /** @description Validation error (bad PDF, oversized, missing fields) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Server error (failed to enqueue or store) */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getMaterial: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                material_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Material found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MaterialStatus"];
                };
            };
            /** @description Missing or invalid material_id */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Material not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getTestV2: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description UUID of the test */
                testId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Test found */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TestItemV2"];
                };
            };
            /** @description Test not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    /**
                     * @example {
                     *       "error": "Test 550e8400-e29b-41d4-a716-446655440000 not found"
                     *     }
                     */
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
